name: tobo
description: A new todo application.
publish_to: none
version: 1.0.0+8
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  awesome_core:
    path: "../flutter_awesome_core"
  flutter_dotenv: "^5.0.2"
  data_plugin:
#    path: ../../plugin/bmob-flutter-sdk/data_plugin
    git:
      url: https://github.com/azhansy/bmob-flutter-sdk.git
      path: data_plugin
      ref: 7e5caf82
  r_dart_library: 0.4.0-nullsafety.0
  simple_animations: "^4.0.0"
  flutter_slidable: "^1.0.0-dev.9"
  flutter_update_dialog: "^2.0.0"
  alarm_calendar: "^0.0.5"
  nova_alarm_plugin:
    path: ../../plugin/nova_alarm_plugin-0.1.0
dependency_overrides:
  flutter_svg: "^0.22.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: "^1.1.7+1"
  flutter_launcher_icons: "^0.9.0"
  floor_generator: "^1.2.0"
  build_runner: "^2.1.2"
flutter_native_splash:
  image: assets/images/logo3x.png
  color: ffffff
  fill: false
flutter_icons:
  image_path: assets/images/logologo.png
  remove_alpha_ios: true
  android: true
  ios: true
flutter:
  uses-material-design: true
  assets:
  - assets/images/background.png
  - assets/images/bg.png
  - assets/images/clock.png
  - assets/images/ic_honor.svg
  - assets/images/ic_honor_header.png
  - assets/images/light-1.png
  - assets/images/light-2.png
  - assets/images/logo.png
  - assets/images/logo.svg
  - assets/images/logo3x.png
  - assets/images/logologo.png
  - ".env"
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets:
  - assets/images
  - ".env"
  fonts: []
