name: tobo
description: A new todo application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  awesome_core:
    path: ../flutter_awesome_core
  flutter_dotenv: "^5.0.2"
  data_plugin:
    git:
      url: https://github.com/azhansy/bmob-flutter-sdk.git
      path: data_plugin


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

