// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
// YOU CAN GET MORE DETAILS ABOUT FLR FROM:
// - https://github.com/Fly-Mix/flr-cli
// - https://github.com/Fly-Mix/flr-vscode-extension
// - https://github.com/Fly-Mix/flr-as-plugin
//

// ignore: unused_import
import 'package:flutter/widgets.dart';
// ignore: unused_import
import 'package:flutter/services.dart' show rootBundle;
// ignore: unused_import
import 'package:path/path.dart' as path;
// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';
// ignore: unused_import
import 'package:r_dart_library/asset_svg.dart';

/// This `R` class is generated and contains references to static asset resources.
class R {
  /// package name: tobo
  static const package = "tobo";

  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();

  /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
  static const svg = _R_Svg();

  /// This `R.text` struct is generated, and contains static references to static text asset resources.
  static const text = _R_Text();

  /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
  static const fontFamily = _R_FontFamily();
}

/// Asset resource’s metadata class.
/// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
/// - packageName：flutter_demo
/// - assetName：assets/images/example.png
/// - fileDirname：assets/images
/// - fileBasename：example.png
/// - fileBasenameNoExtension：example
/// - fileExtname：.png
class AssetResource {
  /// Creates an object to hold the asset resource’s metadata.
  const AssetResource(this.assetName, {this.packageName});

  /// The name of the main asset from the set of asset resources to choose from.
  final String assetName;

  /// The name of the package from which the asset resource is included.
  final String? packageName;

  /// The name used to generate the key to obtain the asset resource. For local assets
  /// this is [assetName], and for assets from packages the [assetName] is
  /// prefixed 'packages/<package_name>/'.
  String get keyName =>
      packageName == null ? assetName : "packages/$packageName/$assetName";

  /// The file basename of the asset resource.
  String get fileBasename {
    final basename = path.basename(assetName);
    return basename;
  }

  /// The no extension file basename of the asset resource.
  String get fileBasenameNoExtension {
    final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
    return basenameWithoutExtension;
  }

  /// The file extension name of the asset resource.
  String get fileExtname {
    final extension = path.extension(assetName);
    return extension;
  }

  /// The directory path name of the asset resource.
  String get fileDirname {
    var dirname = assetName;
    if (packageName != null) {
      final packageStr = "packages/$packageName/";
      dirname = dirname.replaceAll(packageStr, "");
    }
    final filenameStr = "$fileBasename/";
    dirname = dirname.replaceAll(filenameStr, "");
    return dirname;
  }
}

// ignore: camel_case_types
class _R_Image_AssetResource {
  const _R_Image_AssetResource();

  /// asset: assets/images/background.png
  // ignore: non_constant_identifier_names
  final background =
      const AssetResource("assets/images/background.png", packageName: null);

  /// asset: assets/images/bg.png
  // ignore: non_constant_identifier_names
  final bg = const AssetResource("assets/images/bg.png", packageName: null);

  /// asset: assets/images/clock.png
  // ignore: non_constant_identifier_names
  final clock =
      const AssetResource("assets/images/clock.png", packageName: null);

  /// asset: assets/images/ic_splash.png
  // ignore: non_constant_identifier_names
  final ic_splash =
      const AssetResource("assets/images/ic_splash.png", packageName: null);

  /// asset: assets/images/light-1.png
  // ignore: non_constant_identifier_names
  final light_1 =
      const AssetResource("assets/images/light-1.png", packageName: null);

  /// asset: assets/images/light-2.png
  // ignore: non_constant_identifier_names
  final light_2 =
      const AssetResource("assets/images/light-2.png", packageName: null);

  /// asset: assets/images/logo.png
  // ignore: non_constant_identifier_names
  final logo = const AssetResource("assets/images/logo.png", packageName: null);

  /// asset: assets/images/logo3x.png
  // ignore: non_constant_identifier_names
  final logo3x =
      const AssetResource("assets/images/logo3x.png", packageName: null);
}

// ignore: camel_case_types
class _R_Svg_AssetResource {
  const _R_Svg_AssetResource();

  /// asset: assets/images/logo.svg
  // ignore: non_constant_identifier_names
  final logo = const AssetResource("assets/images/logo.svg", packageName: null);
}

// ignore: camel_case_types
class _R_Text_AssetResource {
  const _R_Text_AssetResource();
}

/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
// ignore: camel_case_types
class _R_Image {
  const _R_Image();

  final asset = const _R_Image_AssetResource();

  /// asset: assets/images/background.png
  // ignore: non_constant_identifier_names
  AssetImage background() {
    return AssetImage(asset.background.keyName);
  }

  /// asset: assets/images/bg.png
  // ignore: non_constant_identifier_names
  AssetImage bg() {
    return AssetImage(asset.bg.keyName);
  }

  /// asset: assets/images/clock.png
  // ignore: non_constant_identifier_names
  AssetImage clock() {
    return AssetImage(asset.clock.keyName);
  }

  /// asset: assets/images/ic_splash.png
  // ignore: non_constant_identifier_names
  AssetImage ic_splash() {
    return AssetImage(asset.ic_splash.keyName);
  }

  /// asset: assets/images/light-1.png
  // ignore: non_constant_identifier_names
  AssetImage light_1() {
    return AssetImage(asset.light_1.keyName);
  }

  /// asset: assets/images/light-2.png
  // ignore: non_constant_identifier_names
  AssetImage light_2() {
    return AssetImage(asset.light_2.keyName);
  }

  /// asset: assets/images/logo.png
  // ignore: non_constant_identifier_names
  AssetImage logo() {
    return AssetImage(asset.logo.keyName);
  }

  /// asset: assets/images/logo3x.png
  // ignore: non_constant_identifier_names
  AssetImage logo3x() {
    return AssetImage(asset.logo3x.keyName);
  }
}

/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
// ignore: camel_case_types
class _R_Svg {
  const _R_Svg();

  final asset = const _R_Svg_AssetResource();

  /// asset: assets/images/logo.svg
  // ignore: non_constant_identifier_names
  AssetSvg logo({required double width, required double height}) {
    final imageProvider =
        AssetSvg(asset.logo.keyName, width: width, height: height);
    return imageProvider;
  }
}

/// This `_R_Text` class is generated and contains references to static text asset resources.
// ignore: camel_case_types
class _R_Text {
  const _R_Text();

  final asset = const _R_Text_AssetResource();
}

/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
// ignore: camel_case_types
class _R_FontFamily {
  const _R_FontFamily();
}
